name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies /map
        run: |
          cd map
          npm install
          
      - name: Build /map
        run: |
          cd map
          npm run build

      - name: Install dependencies /projects/util/r-place/map
        run: |
          cd projects/util/r-place/map
          npm install
          
      - name: Build /projects/util/r-place/map
        run: |
          cd projects/util/r-place/map
          npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
